---
- name: play-01 - processing 
  hosts: dev
  tasks:
    - name: Display the message - task-01 
      debug:
        msg: "This is my task - task-01"
    - name: Display the message - task-02
      debug:
        msg: "This is my task - task-02"
    - name: Display the message - task-03 
      debug:
        msg: "This is my task - task-03"
- name: play-02 - processing 
  hosts: qa 
  tasks: 
    - name: Display the message - task-01 of play-02 
      debug:
        msg: "This is my task - task-01 of play-02"
    - name: Display the message - task-02
      debug:
        msg: "This is my task - task-02 of play-02"
        
...
